# Homebrew tap configuration for GoReleaser
# This will be used when we're ready to publish to Homebrew
version: 2

brews:
  - repository:
      owner: jsando
      name: homebrew-tools
      branch: main
      # This token needs to be set as a secret in GitHub
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    name: jb
    
    url_template: "https://github.com/jsando/jb/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    
    description: "The Easier Java Build Tool"
    homepage: "https://github.com/jsando/jb"
    license: "Apache-2.0"
    
    directory: Formula
    
    test: |
      system "#{bin}/jb", "version"
    
    install: |
      bin.install "jb"
    
    dependencies:
      - name: openjdk
        type: optional
        version: "17"