name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            binary_name: jb
            asset_name: jb-linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            binary_name: jb
            asset_name: jb-linux-arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            binary_name: jb.exe
            asset_name: jb-windows-amd64.exe
          - os: macos-latest
            goos: darwin
            goarch: amd64
            binary_name: jb
            asset_name: jb-darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            binary_name: jb
            asset_name: jb-darwin-arm64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -v -o ${{ matrix.binary_name }} -ldflags="-s -w"
    
    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.binary_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Generate changelog
      id: changelog
      run: |
        # Simple changelog generation - can be enhanced later
        echo "## What's Changed" > changelog.md
        echo "" >> changelog.md
        git log --pretty=format:"* %s (%h)" $(git describe --tags --abbrev=0 2>/dev/null || echo "")..HEAD >> changelog.md || echo "First release" >> changelog.md
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: changelog.md
        draft: false
        prerelease: false